### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AwlsomeAlex** [tluck/Lenovo-T420-Clover#10]
The automated scripts you wrote for your T420, what license are they?

**Comment by tluck** [comment]
?

**Comment by AwlsomeAlex** [comment]
Well your scripts at the moment are technically "unlicensed" so anyone could go in, change stuff and say they made it.

**Comment by AwlsomeAlex** [comment]
Also I'm trying to hackintosh another device, think you could help me out?

**Comment by tluck** [comment]
what exactly is the problem?  
...
and the scripts I posted here are not very compelling. I posted them here to share and help others.

**Comment by AwlsomeAlex** [comment]
DSDT Patching for a laptop I'm trying to Hackintosh. Everything works to the point of Battery Indicator, FN Keys, Brightness and Backlit Keyboard. Tried the manual way by RehabMan but SSDT-5 gave me compile errors, could that be why my patched DSDT/SSDT didn't work?
