### ISSUE TITLE
Updating Guide?

### ISSUE THREAD

**Issue by AwlsomeAlex** [tluck/Lenovo-T420-Clover#11]
Hello, I'm working with a friends device and he's not totally thrilled with me just following the Installation Guide and crossing my fingers hoping that the same can be done for updating, which I can't blame him. Is there any **Official** guide I can use to update the Clover Files, Kexts and Clover itself for his system? Thanks!

**Comment by tluck** [comment]
well there are lots of guides - rehabman has the most thorough guide to explain various pieces. and support for a wide variety of systems. what is your friends system?

**Comment by AwlsomeAlex** [comment]
I mean like updating your files, for everytime you release an update for the T420.

**Comment by AwlsomeAlex** [comment]
Like he’s using the Clover, Kexts and DSDT from a release last June but I want to update all the files to the newest one (in hopes Graphical Glitches will disappear)

**Comment by AwlsomeAlex** [comment]
Also is your files confirmed working for Mojave?

I apologize when I emphasized official, I meant like a guide you released.

**Comment by tluck** [comment]
yes i am using mojave. with the procedure outlined in the insanelymac thread.  the best way to update is to replace the EFI folder with the contents of the zip. of course if you make changes, first you merge in any values specific to your system in config.plist, which maybe ROM/MLB variables. or add other kexts or kext patches.

**Comment by AwlsomeAlex** [comment]
Appreciate it. I'm just going to wait for Mojave to release on the 24th, which will give me an excuse to use the most up-to-date files.
