### ISSUE TITLE
This version of macOS 10.14 cannot be installed on this computer.

### ISSUE THREAD

**Issue by afdallah** [tluck/Lenovo-T420-Clover#13]
Hi, tluck,
I am trying to upgrade my Thinkpad T420 (High Sierra) to Mojave, but every time I hit the download button I always get this message.

**We could not complete your purchase.**
This version of macOS 10.14 cannot be installed on this computer.

I have read your post multiple time but yet I still couldn't get any clue, is it means that Thinkpad t420 can not upgrade to Mojave?

thank you

**Comment by tluck** [comment]
if you are on a MacbookPro8,1 then Mojave is not supported.  if you switch to the config.mojave.plist,  it changes your Model/Product to MBP11,1 which is a supported platform. So install the latest ESP zip and move config.mojave.plist to config.plist (and merge in any items you may need - ROM/MLB an LCD properties etc). Remember to update your ESP before you do the install. And preserve (copy) the /S/L/E HD3000 and SNB kexts to a good location. and you should be able download and go.
