### ISSUE TITLE
Thinkpad trackpad not detected

### ISSUE THREAD

**Issue by afdallah** [tluck/Lenovo-T420-Clover#15]
Recently I downgraded my ThinkPad t420 from High Sierra to Sierra, due to freeze and glitch that often happened.

I did a clean install for this Sierra, but I don't know why the trackpad settings do not show up, instead, it shows Bluetooth trackpad pairing things and other issues like the Battery indicator don't want to show up, brightness settings disappear.

Here is the screenshot.
[Screenshot](https://www.evernote.com/client/snv?noteGuid=b4e33a72-c69d-43bd-803d-38c49df987f9&noteKey=e163f22405716d9b&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs639%2Fsh%2Fb4e33a72-c69d-43bd-803d-38c49df987f9%2Fe163f22405716d9b&exp=ENB3538)

Is this a known issue or something else? 

Thank you

**Update [solved]**
It looks like some of kext on the version r4678 are not compatible with my sierra, so after trial and error  I replace ACPIBatteryManager.kext, VoodooPS2Controller.kext, AppleBacklightInjector.kext with the older version, and everything is work again. 
please close this issue

**Comment by tluck** [comment]
thats what i figured.  glad its working for you
