### ISSUE TITLE
t420 mac High sierra 10.13.6 freeze冻屏

### ISSUE THREAD

**Issue by cbingos** [tluck/Lenovo-T420-Clover#16]
t420 mac High sierra 10.13.6 freeze冻屏

safari 一移动或缩小就冻屏，

**Comment by cbingos** [comment]
我使用的是1600*900.2e2.plist 配置文件，现在测试下来发现，浏览器chrome,safari 只要轻微拖动就会冻屏，鼠标可以正常使用，其它配置完全按照文档中的来。

**Comment by tluck** [comment]
maybe try the other 2e3 config.plist then? i have been using that one. 

what is your LCD brand/type? if not AUO then dont inject a fake EDID

**Comment by cbingos** [comment]
Thanks for your reply, I have solved the problem with the 1600*900.2e2.plist configuration file.

**Comment by thomas-hcb** [comment]
How did you solve this? I have been facing with freezing issue occasonally, and still can't figure out how to overcome this. I tried 2 release version 15-Oct-2018 & 31-Oct-2018 with 1600*900.2e2.plist and the rest 2 but the freeze & glitches still persist. 

Was there any older release that brings stability to High Sierra?

For now I downgraded to Sierra for reviewing whether I still face with freezing & gliches or not. 

Thank for your answer in advance.

**Comment by MarekLg** [comment]
From what i gathered it has something to do with hd3000 in combination with the screen from aou.
But as I don’t have the money to change either of those I can’t tell if it actually would solve the problem.

**Comment by cbingos** [comment]
I am using 1600*900.2e2.plist in this Lenovo-T420-Clover-2018.10.15, and there are no other changes; other steps refer to https://www.insanelymac.com/forum/topic/285678-lenovo-thinkpad-T420-with-uefi-only/?page=20&tab=comments#comment-1952283

**Comment by tluck** [comment]
i am using a fake EDID that I call the 2e3 config.plist etc (vs 2e2). This seems to hang a bit less.
