### ISSUE TITLE
Screen brightness issues when using the new pack(Lenovo-T420-Clover-2019.01.24.zip)

### ISSUE THREAD

**Issue by jenyunhuang** [tluck/Lenovo-T420-Clover#18]
Hi tluck

Very happy to see the you release new pack.
But using this new pack, the screen brightness become to unnormal. 
When the computer from sleep to weak up or screen off to on.
The screen brightness vary dark to normal.
How I can fix it?

**Comment by tluck** [comment]
hmm... did you still have the framebuffer patch that changes max to 0x1312 vs 0x710
i used to change max Level and VGA port in 1 clover patch. 
now the patch is just for VGA as 4th port

ioreg -l should look like this for PNLF

    | +-o PNLF@0  <class IOACPIPlatformDevice, id 0x10000015b, registered, matched, active, busy 0 (9 ms), retain 9>
    | | | {
    | | |   "compatible" = <"backlight">
    | | |   "AppleBacklightAtBoot" = 1808
    | | |   "AppleMaxBrightness" = 1808
    | | |   "_UID" = "14"
    | | |   "device-properties" = {"acpi-device"="IOACPIPlatformDevice is not serializable","acpi-path"="IOACPIPlane:/_SB/PCI0@0/IGPU@20000/PNLF@0"}
    | | |   "ApplePanelRawBrightness" = 1808
    | | |   "_STA" = 11
    | | |   "_ADR" = 0
    | | |   "name" = <"APP0002">

**Comment by jenyunhuang** [comment]
ya, solved it
thanks

**Comment by tluck** [comment]
cool.
