### ISSUE TITLE
Black screen after loading bar T420 1080P Mod

### ISSUE THREAD

**Issue by msoffice95** [tluck/Lenovo-T420-Clover#19]
Hi,
i am having issues with loading on a T420 that has had a 1080p mod done. 
After the apple loading bar it goes to a black screen and does not come online i have tried a couple different guides and none of them have worked is this to do with the mod or maybe i am missing something critical?
Spec: T420
i7 2670qm
12GB ram
120gb ssd
1080p AUO IPS screen

**Comment by jenyunhuang** [comment]
do you have inject your edid?

**Comment by tluck** [comment]
ah good thinking- jenyunhuang. 
msoffice96 - did you remove/replace the EDID from the config.plist (that would be for 1600x900)?

**Comment by jenyunhuang** [comment]
Because I have same issue using your config without change EDID.
I have two Laptop X220 with ips & T420s with mod FHD.
It's resolved with replace the EDID.

**Comment by wklxd** [comment]
> Because I have same issue using your config without change EDID.
> I have two Laptop X220 with ips & T420s with mod FHD.
> It's resolved with replace the EDID.

hi jenyunhuang, which EDID you used for T420's 1080P
i'd like to change my screen to 1080P

**Comment by jenyunhuang** [comment]
> > Because I have same issue using your config without change EDID.
> > I have two Laptop X220 with ips & T420s with mod FHD.
> > It's resolved with replace the EDID.
> 
> hi jenyunhuang, which EDID you used for T420's 1080P
> i'd like to change my screen to 1080P

My T420s mod 1080p edid
AP///////wAwrqNAAAAAAAwZAQSVHxF46oVFpFpUoScMUFQAAAABAQEBAQEBAQEBAQEBAQEBKTaAoHA4H0AwIDUANa8QAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDRCTvRCTseCgAGrz0SAAAA/gBCMTQwSEFOMDEuMiAKADc=

**Comment by dino00782** [comment]
I have same question，I have replaced T420i screen to 1080p AUO IPS ，This device was mod to  manufacturer ID：B140HAN01.2   Monitor ID：LEN40A3   
Would you do me a favor?
![IMG_20200502_184033](https://user-images.githubusercontent.com/26727840/80910838-e36c6800-8d64-11ea-83c2-bd6486bb29fe.jpg)
![IMG_20200502_192453](https://user-images.githubusercontent.com/26727840/80910839-e6ffef00-8d64-11ea-83f3-2be7cf93bd0c.jpg)
![1588498303400](https://user-images.githubusercontent.com/26727840/80910840-e9624900-8d64-11ea-995e-3ac6c9ea59b6.jpg)

**Comment by dino00782** [comment]
![1588498303400](https://user-images.githubusercontent.com/26727840/80910967-d56b1700-8d65-11ea-8636-ff1e73930af7.jpg)

**Comment by jenyunhuang** [comment]
> I have same question，I have replaced T420i screen to 1080p AUO IPS ，This device was mod to manufacturer ID：B140HAN01.2 Monitor ID：LEN40A3
> Would you do me a favor?
> ![IMG_20200502_184033](https://user-images.githubusercontent.com/26727840/80910838-e36c6800-8d64-11ea-83c2-bd6486bb29fe.jpg)
> ![IMG_20200502_192453](https://user-images.githubusercontent.com/26727840/80910839-e6ffef00-8d64-11ea-83f3-2be7cf93bd0c.jpg)
> ![1588498303400](https://user-images.githubusercontent.com/26727840/80910840-e9624900-8d64-11ea-995e-3ac6c9ea59b6.jpg)

change your config edid "
AP///////wAwrqNAAAAAAAwZAQSVHxF46oVFpFpUoScMUFQAAAABAQEBAQEBAQEBAQEBAQEBKTaAoHA4H0AwIDUANa8QAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDRCTvRCTseCgAGrz0SAAAA/gBCMTQwSEFOMDEuMiAKADc=
"

**Comment by dino00782** [comment]
Thanks！Let me try~~~
