### ISSUE TITLE
T420 10.14 HD3000 QE、IC

### ISSUE THREAD

**Issue by unmat328** [tluck/Lenovo-T420-Clover#21]
Hello, I am a black apple lover in China. I use your EFI very well.

T420 can be installed normally with the latest EFI, but HD3000 graphics driver is not perfect.

DOCK column is not translucent. LAUNCHPAD Cardon proves that HD3000 does not turn on QE、 IC 

I hope the developer can perfect the driver. Thank you.

**Comment by tluck** [comment]
well. read my guide on insanelymac to get Full HD 3000 gfx to work on 10.14.0->10.14.4
you need to install the HighSierra HD3000 kexts to get full gfx on Mojave.

**Comment by unmat328** [comment]
Thank you very much. I upgraded from 10.13 to 10.14. Then I used the method you provided in the forum. At present, transparency is a problem in light color. In the process of using, screen lines will appear. It will be 10.15 soon. Looking forward to your new tutorial, Chinese netizens respectfully.





------------------ 原始邮件 ------------------
发件人: "tluck"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 上午10:55
收件人: "tluck/Lenovo-T420-Clover"<Lenovo-T420-Clover@noreply.github.com>;
抄送: "faior"<faior@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tluck/Lenovo-T420-Clover] T420 10.14 HD3000 QE、IC (#21)




well. read my guide on insanelymac to get Full HD 3000 gfx to work on 10.14.0->10.14.4
 you need to install the HighSierra HD3000 kexts to get full gfx on Mojave.
