### ISSUE TITLE
my t420 cant install Mojave and Catalina with release 2020-March-15

### ISSUE THREAD

**Issue by kevinboxz** [tluck/Lenovo-T420-Clover#24]
The computer configuration is as follows:

- cpu i7 2630
- RAM 8G
- HD built-in
- Wireless card changed to BCM4322
- Optical drive changed to hard drive
- Resolution 1600x900

When I installed macos mojave 10.14.6,it told me that the computer could not install this OS.
Which configuration should I modify?

**Comment by tluck** [comment]
are you using the dosdude1 method of installing? you will see such notices since Mojave and Catalina are not supported on MBP8,1 models.
