### ISSUE TITLE
Oc boot black screen reboot 

### ISSUE THREAD

**Issue by unmat328** [tluck/Lenovo-T420-Clover#26]
The methods are correct, guide into the system interface, power off and restart.

**Comment by tluck** [comment]
was there a question here? or did you resolve it?

**Comment by unmat328** [comment]
> 这里有问题吗？还是解决了？

Did not solve, oc boot or to enter the system that step, the black screen restart.

**Comment by tluck** [comment]
OC is black screen? does it  start to boot OC? 
what is your system type and LCD resolution. this is set up for 1600x900 LCD.

**Comment by unmat328** [comment]
It's all normal, that is, to the point of entering the interface, the power is turned off and restarted. Is 1600 * 900, the core graphics card.

**Comment by dino00782** [comment]
Thanks a lot! It solved！




Thanks &amp; Best Regards
 
Dino.zhu
 
E-Mail:&nbsp;16605283@qq.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"unmat328"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 中午12:15
收件人:&nbsp;"tluck/Lenovo-T420-Clover"<Lenovo-T420-Clover@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [tluck/Lenovo-T420-Clover] Oc boot black screen reboot  (#26)





 
It's all normal, that is, to the point of entering the interface, the power is turned off and restarted. Is 1600 * 900, the core graphics card.

**Comment by tluck** [comment]
what did you need to do to fix it?

**Comment by unmat328** [comment]
> 您需要做什么来解决它？

Did not solve, clover is also the previous version is better, the new version of the browser has a screen line.

**Comment by unmat328** [comment]
![Uploading 4C618B1D-B433-4062-9A57-062C0B8C00B8.jpeg…]()
![2DB37DB7-F740-45B0-8C69-EDDD108C2E75](https://user-images.githubusercontent.com/50646332/83212441-34b81d80-a192-11ea-8bd4-1b918203598c.jpeg)
![Uploading 2EB6AE66-571C-4741-9BC7-43E39D492DF6.jpeg…]()

**Comment by unmat328** [comment]
![63C973F5-80F1-4387-B924-AD18C854D64D](https://user-images.githubusercontent.com/50646332/83212543-7779f580-a192-11ea-8fb7-fc507d095f99.jpeg)

**Comment by tluck** [comment]
yeah maybe you should stay with clover if you can get that to work for you.  OC works ok for me.
