### ISSUE TITLE
Unable to update to Catalina newer than 10.15.3

### ISSUE THREAD

**Issue by sghng** [tluck/Lenovo-T420-Clover#28]
I'm using T420, with 1366x768 screen, the newest release from this repo as `EFI` files, and accordingly using `config.1366x768.plist` as my `config.plist`. Nothing else is modified.

So far, Catalina 10.15.3 functions normally on my laptop, but I cannot install any versions of Catalina newer than this.

---

For creating a bootable flash drive for installing using Catalina patcher, the installing process gets stuck at `Service exited with abnormal code 1`, `Service only ran for 0 seconds, pushing respawn`, and keeps on looping in such exceptions.

---

I also tried update by changing the model in `config.plist` to `MacBookPro9,1`, so that I'm able to install combo updates downloaded from Apple.com, and this did work. However, when booting system after update, some unknown errors occurred, and it shows `Attempting system restart...`, and it just keeps on restarting. 

---

Is it able to install newer versions of Catalina on T420?

**Comment by tluck** [comment]
to install Mojave or Catalina you need to use the dosdude1 installer method. it patches the installer on USB to make it work with HD3000
