### ISSUE TITLE
Terrible Trackpad

### ISSUE THREAD

**Issue by SuperSkull** [tluck/Lenovo-T420-Clover#3]
Touchpoint is ok to use but trackpad is terrible compare to previous version

**Comment by jenyunhuang** [comment]
me too

**Comment by tluck** [comment]
i had some jumpiness lagginess until i changed some settings. did you put the SSDT-T420-PS2K file in your ACPI/patched folder?

**Comment by jenyunhuang** [comment]
Yes. I had put the SSDT-T420-PS2K.aml file in the patched folder.

**Comment by tluck** [comment]
can you provide more information on how the trackpad behaves with this version?

**Comment by tluck** [comment]
oh. did you replace your DSDT.aml file in patched too?

**Comment by jenyunhuang** [comment]
So need use the new dsdt.aml file?
Very fine for replace the new DSDT.aml file.
Thank

**Comment by tluck** [comment]
cool. glad it works.

**Comment by tluck** [comment]
all the new DSDT files are missing the _DSM (method) for device PS2K - which is now provided by the SSDT-T420-PS2K.

**Comment by badsirius** [comment]
What to do if the specs is **T420s**？
the T420s trackpad doesn't work after putting the **SSDT-T420-PS2K.am**l to **Patched** folder.

**Comment by tluck** [comment]
did you change your DSDT device PS2K method _DSM to XDSM ? this way the SSDT method will be used?

**Comment by badsirius** [comment]
It works.
The **dsdt.aml** in /Clover/ACPI.T420s this repo provided **doesn't** changed the PS2K method _DSM to XDMS.

My T420s trackpad functions well after following your guide (also put the SSDT-T420s-PS2K into 'Patched' folder). 
Thanks a lot.
