### ISSUE TITLE
T420s(i7-2640M, 8GB RAM, 120GB SSD, 1600x900 LCD)

### ISSUE THREAD

**Issue by bulog** [tluck/Lenovo-T420-Clover#32]
Hi tluck

Thanks for your files, and my T420s(i7-2640M, 8GB RAM, 120GB SSD, 1600x900 LCD) works well on macOS 10.15.7 with CLOVER files latest uploaded(10 days ago), except the keyboard F1 became F14, and F2 became F15, don't know why, there was no problem with the latest release(11 Dec, 2020), but I switch back to (11 Dec, 2020), the F1, and F2 key on the keyboard still not work, do I need to do something after change the files?

About OC boot, do I need to copy the `ACPI.T420s` from `CLOVER` folder to the `OC` folder and rename to `ACPI`?

I tried the OC boot of files on 11 Dec, 2020, it's works fine without audio, and can not sleep/wakeup

Also I tried the OC files(10 days ago), but it can not find the current macOS boot volume(I put the files in the USB disk, this works for the OC files on 11 Dec, 2020).

Thanks in advance
Ady

**Comment by tluck** [comment]
there isnt really any advantage with OC over Clover for this case IMO.  I have the exact same features/functionality. 

The VoodooPS2 files include a mapping for F1/F2 for brightness and F10/F11/F12 for volume control similar to a mac keyboard etc. 

For ACPI yes the DSDT and SSDT files are needed for OC. - you may need to provide the SSDT-CpuPM that matches your cpu.

hmm. i dont know offhand what changed in these versions/commits. but I can boot from Clover or OC by just changing the ESP/EFI/BOOT contents on the HD. i recall you may have a USB3 port - but not sure if that is going to be usable.

**Comment by bulog** [comment]
Thanks very much for your reply.
Don't know what happened, I will try to use the ACPI files of T420s.
I tried to restore the system via Time machine 2 weeks ago, I don’t know if it’s because of this

And except F1/F2, the F10/F11/F12 for volume control works perfect.

I Also tried to ESP/EFI/BOOT and OC folder on the macOS SSD, it's did not boot, can not show the macOS boot volume, but the old OC files(11 Dec, 2020) works 

About the USB 3.0 port, it's not works, I plug the USB disk to the left side of T420s(USB 2.0 port)
