### ISSUE TITLE
catalina 10.15.7 no trackpad found 

### ISSUE THREAD

**Issue by shaodt0716A** [tluck/Lenovo-T420-Clover#33]
HI
tluck.
Please help. Check out the strange question below.

T420i Catalina 10.15.7

Now the touch pad two finger gesture should be available, which means that the touch pad has been driven, but there is no interface [no trackpad found] in the settings, and the touch pad cannot be clicked.

May I ask which ones need to be changed which can be clicked and displayed on the trackpad window.

Thanks!

**Comment by tluck** [comment]
if the trackpad is not showing up, then maybe you need to see how you are identifying the device.  the kexts are looking for keys: LENOVO and T420 - which are defined in the DSDT/SSDT files

// tjl-begin - add this Method
                    Method (XDSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                    {   
                        Store (Package (0x06)
                            {   
                                "RM,oem-id",
                                "LENOVO", 
                                "RM,oem-table-id",
                                "T420", 
                                "AAPL,has-embedded-fn-keys",
                                Unicode ("\x01")
                            }, Local0)
                        DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                        Return (Local0)
                    }
// tjl-end      

$ ioreg -l|grep RM,o
    | | |   "RM,oem-id" = "LENOVO"
    | | |   "device-properties" = {"RM,oem-table-id"="T420","RM,oem-id"="LENOVO"}
    | | |   "RM,oem-table-id" = "T420"
