### ISSUE TITLE
t420 i5 2520 安装完美 但是玩着玩着就会死机卡屏

### ISSUE THREAD

**Issue by 314200108** [tluck/Lenovo-T420-Clover#35]
t420 i5 2520 安装完美 但是玩着玩着就会死机卡屏  中途我装了个无线网卡  然后网卡可以用了  而且开机画面有一道黑线 进系统没有 玩着玩着会卡屏

**Comment by tluck** [comment]
The installation is perfect, but the screen will freeze when playing. I installed a wireless network card in the middle and the network card can be used, and there is a black line on the boot screen. It does not enter the system. It will freeze when playing.

well you maybe running into the common gfx hang issue. in the log you may see this 

```
8/21/11 2:29:56.000 PM	kernel	****  Debug info for apparent hang in Main graphics engine  ****
8/21/11 2:29:56.000 PM	kernel	ring head    = 0x01e00df4, wrap count = 0x f
8/21/11 2:29:56.000 PM	kernel	ring tail    = 0x00000ef8 ring control = 0x00003801   enabled, auto report disabled,  waiting, semaphore not waiting, length = 0x004 4KB pages
8/21/11 2:29:56.000 PM	kernel	timestamps = 0x0fa2
8/21/11 2:29:56.000 PM	kernel	Semaphore register values:
8/21/11 2:29:56.000 PM	kernel	VRSYNC: (0x12044) = 0xfa2
8/21/11 2:29:56.000 PM	kernel	BRSYNC: (0x22040) = 0x0
8/21/11 2:29:56.000 PM	kernel	RVSYNC: (0x 2040) = 0x0
8/21/11 2:29:56.000 PM	kernel	BVSYNC: (0x22044) = 0x0
8/21/11 2:29:56.000 PM	kernel	RBSYNC: (0x 2044) = 0x1
8/21/11 2:29:56.000 PM	kernel	VBSYNC: (0x12040) = 0x0
```

inject an EDID can help.

**Comment by 314200108** [comment]
我试了半天都不行，修改完后启动就有两个苹果的启动项都起不来，我文件给你方便帮我看下？ 看下我哪里修改下有问题，最好是你帮忙修改下看看可以吗

[显示器文件.zip](https://github.com/tluck/Lenovo-T420-Clover/files/6819763/default.zip)

**Comment by 314200108** [comment]
现在能改的我都改了 还是花屏  我内存是4g的是不是内存太低的原因，显卡我从384改到了1g了，大哥还有什么办法吗？

**Comment by tluck** [comment]
perhaps replace the config.plist (which has EDID-366) with this one: config.EDID-2e2.plist

**Comment by 314200108** [comment]
你好文件在哪里  还是你之前包里的config.EDID-2e2.plist这个文件可以？

**Comment by tluck** [comment]
here: https://github.com/tluck/Lenovo-T420-Clover/tree/master/EFI/CLOVER 

there are 3 options:

 config.EDID-{2e2,2e3,366}.plist - any can work for 1600x900 LCD.... 2e2 maybe the best?

In your HD EFI
rename config.plist to old.plist
rename config.EDID-2e2.plist to config.plist

**Comment by 314200108** [comment]
好的 我已经修改 我先试一下，不行在联系您，谢谢！

**Comment by 314200108** [comment]
还是不行，还有别的办法吗？

**Comment by tluck** [comment]
what is not working?

**Comment by 314200108** [comment]
还是跟之前一样卡屏！

**Comment by 314200108** [comment]
您有telegram吗方便加下咨询下吗？

**Comment by tluck** [comment]
what version of the macOS are you using? with Sierra these problems usually don't happen. but with High Sierra and later versions, the graphics on a system with low memory can hang or freeze.

**Comment by 314200108** [comment]
10.13.6

**Comment by 314200108** [comment]
![771097BCC57F1603B40FEBBAD352F887](https://user-images.githubusercontent.com/53009757/125976263-2266574c-8f72-46f4-af4c-aca93dcbe5e8.png)
这个是我之前没有改显存时候的照片

**Comment by tluck** [comment]
perhaps use this patch - will change Intel HD Graphics **384 MB** to Intel HD Graphics **1024 MB**

```
			<dict>
				<key>Comment</key>
				<string>from 384MB to 1024MB memory</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				x0XQAAAAGA==
				</data>
				<key>MatchOS</key>
				<string>10.13.x,10.14.x,10.15.x</string>
				<key>Name</key>
				<string>com.apple.driver.AppleIntelSNBGraphicsFB</string>
				<key>Replace</key>
				<data>
				x0XQAAAAQA==
				</data>
			</dict>
```
and check your edid was updated - on command line, run this to see if the output matches

**$ ioreg -l|grep yEDID**
    | |   | | |       "IODisplayEDID" = <00ffffffffffff00**30e4e202**0000000001140103801f1178e233859956559127175054000000010101010101010101010101010101018025408060841a303020350036ae10000018000000000000000000000000000000000000000000fe004c656e6f766f0a202020202020000000fe0031363030783930300a2020202000ad>

**Comment by 314200108** [comment]
本人小白 不会弄  能不能把成品的文件发给我！

**Comment by 314200108** [comment]
我用不用装个低版本的系统 比如10.12.6会好？

**Comment by tluck** [comment]
Sierra was the best. so yes. try that out.

**Comment by 314200108** [comment]
10.12.6就直接用您的包就行了是吗 还用改edid吗

**Comment by 314200108** [comment]
好的 那我试试看 还不行就只能放弃了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月17日(星期六) 上午7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tluck/Lenovo-T420-Clover] t420 i5 2520 安装完美 但是玩着玩着就会死机卡屏 (#35)






塞拉是最棒的，所以是的，试试看。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by tluck** [comment]
config.EDID-366.plist seems to work the best after some more testing.
