### ISSUE TITLE
No graphics after Apple logo ant status bar. Live USB Installer.

### ISSUE THREAD

**Issue by unix-vokar** [tluck/Lenovo-T420-Clover#36]
Black screen after the apple logo and status bar. Using the 1366x768 TN panel on the t420. i5-2520m, 1 tb ssd.

**Comment by tluck** [comment]
what macOS version? and if on Mojave or Catalina did you use the dosdude1 method to create the installer? last question - did you replace config.plist with the config.1366x768.plist version:

**Comment by unix-vokar** [comment]
Using High Sierra. Tried it with opencore and clover. Where is plist? Couldn't find it.

**Comment by tluck** [comment]
what? the files are in this repo under EFI/CLOVER/config.plist - there are several options in this folder. Replace config.plist with 1366x768.plist for your box.

**Comment by unix-vokar** [comment]
Will try it out. How about opencore? Appreciate your time.

**Comment by unix-vokar** [comment]
So how would the folder structure look like for the *.plist?

**Comment by unix-vokar** [comment]
Using 12G of RAM.

**Comment by unix-vokar** [comment]
Tried renaming the plist. How should I replace it?

**Comment by tluck** [comment]
uh?? i presume you copied this repo to your USB so on the command line:

1) mount your USB ESP or disk ESP

2) rename the file
cd /Volumes/ESP/EFI/CLOVER
mv config.plist config.orig.plist
mv config.1366x768.plist config.plist

3) boot from USB to install macOS

**Comment by unix-vokar** [comment]
Thanks. I actually was able to install High Sierra successfully! Thank you. I used Open Core and edited the plist. Removed the values for the Graphics (Dual Link and something else, it was right underneath/above). Have a issue with absolutely no network. Opening another issue.
