### ISSUE TITLE
No Internet.

### ISSUE THREAD

**Issue by unix-vokar** [tluck/Lenovo-T420-Clover#37]
I have no internet at all using Open Core. Working High Sierra. Here is my hardware:

Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (Lewisville)
Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak]
Resolution: 1366x768
CPU: Intel i5-2520M
Laptop: T420

Any suggestions?

**Comment by tluck** [comment]
if you are running HighSierra and booting with OC, then you need to repace the IntelMausiEthernet.kext with the one from the CLOVER/Kext/10.13 folder. this one is compatible with HighSierra.

**Comment by unix-vokar** [comment]
Running. Fixed. I managed to get the wifi working through the iwctl kext.
