### ISSUE TITLE
Is this Big Sur compatible?

### ISSUE THREAD

**Issue by MultimediaLucario** [tluck/Lenovo-T420-Clover#38]
My name is Tyler aka MultimediaLucario on YouTube. I am planning on hackintoshing a ThinkPad T420 for a friend of mine as a Christmas present. Anyways, I was just wondering if the OpenCore EFI files will give the T420 the ability to run macOS Big Sur or higher and have everything work with little to no issues?

**Comment by tluck** [comment]
Hi Tyler. To answer your question. No. 
The highest/last release for the T420 (an HD 3000 gfx machine) is able to go - using the clever dosdude1 patching mechanism - is Catalina. 10.15.7 is the end of the road for this box.

**Comment by MultimediaLucario** [comment]
Okay. Thanks for clearing that up.
