### ISSUE TITLE
Is it possible to make the DVI on docking station work?

### ISSUE THREAD

**Issue by badsirius** [tluck/Lenovo-T420-Clover#4]
I replaced the origin display screen(1600x900) to WQHD display which connect to the DVI port on docking station of T420s.

When using the EFI on my T420s, the macOS High Sierra can boot well but can't show anything( the display screen is "Black").

**Comment by tluck** [comment]
yes. you can remove the framebuffer patch - which swaps out the DVI dock port for on board vga.

**Comment by badsirius** [comment]
It Works!
After delete this patch belowed in 'KextsToPatch', The mod WQHD display screen can display **but  it blurred frequently**. 
```
<dict>
	<key>Comment</key>
	<string>Patch Framebuffer Levels and Replace 4th port with VGA</string>
	<key>Disabled</key>
	<false/>
	<key>Find</key>
	<data>
	AQIEABAHAAAQBwAABQMAAAIAAAAwAAAAAgUAAAAEAAAH
	AAAAAwQAAAAEAAAJAAAABAYAAAAEAAAJAAAA
	</data>
	<key>Name</key>
	<string>com.apple.driver.AppleIntelSNBGraphicsFB</string>
	<key>Replace</key>
	<data>
	AQIEABITAAASEwAABQMAAAIAAAAwAAAAAgUAAAAEAAAH
	AAAAAwQAAAAEAAAJAAAABgIAAAABAAAJAAAA
	</data>
</dict>
```

and I drag the [IntelGraphicsFixup.kext](https://github.com/lvs1974/IntelGraphicsFixup) into /EFI/Clover/kexts/Other
the mod WQHD display screen work well, not blurred any more.

**Comment by badsirius** [comment]
Hi, tluck. 
After upgrading to Mojave, I also disable the patch for framebuffer but didn’t install the kexts related to the HD3000. 
With that, T420s can boot successfully and the screen can display functionally (not ’black’) but the HD3000 didn’t driver. 

When I installed all the  kexts related to the HD3000 to /S/L/E by Kext Utility. Reboot the T420s, the screen is black again. The DVI port on dock-station was swapped out again, but the patch for framebuffer was disabled in config.plist. 

How can I make the DVI on dock-station work again if my T420s upgrade to Mojave?


Thanks in advance.

**Comment by tluck** [comment]
seems like you had removed the patch to use VGA before and that should be the same. maybe remove WhatEvergreen.kext for a test?

for me with the patching i get this: 

$ ioreg -l|grep connector
    | |   | | |   "connector-type" = <02000000>
    | |   | | |   "connector-type" = <00040000>
    | |   | | |   "connector-type" = <00040000>
    | |   | | |   "connector-type" = <00010000>

0200=LCD (LVDS)
0004=DP
0008=HDMI
0001=VGA
