### ISSUE TITLE
ThinkPad Theme for OC?

### ISSUE THREAD

**Issue by jamesyym** [tluck/Lenovo-T420-Clover#41]
I'd love this ThinkPad Theme with Clover.
Is there any way to convert it to support OC theme?
Thanks a lot.

**Comment by tluck** [comment]
this tool should be able to build a OC (OpenCanopy) theme. https://github.com/chris1111/OpenCanopy-Generator

**Comment by jamesyym** [comment]
Thank you, I will try.
