### ISSUE TITLE
Can you provide a t520‘s config with 1920 * 1080?

### ISSUE THREAD

**Issue by wxp11** [tluck/Lenovo-T420-Clover#5]
Can you provide a t520‘s config with 1920 * 1080?  thank you。

**Comment by tluck** [comment]
i would expect the t420 and t520 to be pretty much the same?

**Comment by wxp11** [comment]
T420 and t520 are almost the same except for size。i5-2520M，HD3000... 
But my t520's screen resolution is 1920x1080, and it has nvs4200m graphics card,And I replaced the screen  because the original screen is broken(Both resolutions are 1920x1080).
I used the T420‘s efi you provided, injected edid to config and dsdt, Shielded discrete graphics. However,the progress bar is not finished and screen is dark when I start from the U disk.
Do you know what this is about?

**Comment by tluck** [comment]
so you inject your own EDID ? not sure why it would be black screen? make sure your DSDT is correct and the try not inject gfx by clover. my dsdt works either way for me. maybe drop MCFG table?
