### ISSUE TITLE
iMessage Support?

### ISSUE THREAD

**Issue by AwlsomeAlex** [tluck/Lenovo-T420-Clover#6]
I tried using TonyMacx86's guide for an iMessage fix for Hackintoshes, however when I applied it it brought me to the Apple Logo frozen on the screen (No Longer Booting). Can you provide a guide on how to fix it?

**Comment by tluck** [comment]
i dont think the guide is wrong. it could be the way you added the variables broke the config.plist file?

**Comment by AwlsomeAlex** [comment]
Im not sure, I used Clover Configurator and did it the way it explained, still broke it.

**Comment by tluck** [comment]
Yeah that tool will create an improperly formated file when adding MLB or ROM values

**Comment by AwlsomeAlex** [comment]
So what do you recommend I do?

**Comment by tluck** [comment]
well. you can edit the values with a better plist editor? i use plistedit pro - or just use vi or textedit. the RtVariable section looks like this:

	<key>RtVariables</key>
	<dict>
		<key>BooterConfig</key>
		<string>0x28</string>
		<key>CsrActiveConfig</key>
		<string>0x3C3</string>
		<key>MLB</key>
		<string>XXXXXXX</string>
		<key>ROM</key>
		<string>XXXXXX</string>
	</dict>
