### ISSUE TITLE
No sound input

### ISSUE THREAD

**Issue by jenyunhuang** [tluck/Lenovo-T420-Clover#8]
Hi tluck

I using the your new version Clover r4600 and no sound input(mic).

**Comment by tluck** [comment]
Ok.  i will check on my system later today.

**Comment by tluck** [comment]
can you try these revised Lilu/AppleALC kexts? just reposed them today July 20 - they seem to work better now?

**Comment by jenyunhuang** [comment]
Now it is ok, Thank
