### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by AwlsomeAlex** [tluck/Lenovo-T420-Clover#9]
I've noticed heavy graphical websites will sometimes have glitches with black flickering and such, and even some games will have unstable graphical interfaces. Is there a fix for this? This is a ThinkPad T420 with a 1600x900 display updated to the latest release (8-9-18).

**Comment by tluck** [comment]
some have the same thing on occasion.  with 1 of my T420 systems i get glitches and the other with a different LCD LG works without glitches.

**Comment by AwlsomeAlex** [comment]
@tluck Just to let you know, when I included WhateverGreen in the Others folder for CLOVER, I no longer had these issues. Ill let you know if they come up again but if not, might be your fix. ;)
